version: '3'
services:
  web:
    restart: always
    build: ./web
    expose:
      - "5000"
    volumes:
      - static:/uwsgi/app/static
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - web:web

volumes:
  static:

