version: '3'
services:
  web:
    container_name: web1
    restart: always
    build: ./web
    expose:
      - "9000"
    volumes:
      - ./web/static:/src/app/static
  nginx:
    container_name: nginx1
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - web

volumes:
  static:

